### PR TITLE
updated demo diagram and added deployment yaml

### PR DESCRIPTION
**Pull request by yujinkim-msft**
updated the diagram with new NodeID and added deployment yamls to simplify creation of OPC PLC servers.

### CODE REVIEW

**Comment by kate-goldenring** [comment]
nit: can we keep the diagram name `opcua-demo-diagram`? Also the updated diagram seems malformed on the `SomeServer0` and `1`. may just be my viewer, though

**Comment by yujinkim-msft** [comment]
> nit: can we keep the diagram name `opcua-demo-diagram`? Also the updated diagram seems malformed on the `SomeServer0` and `1`. may just be my viewer, though

@kate-goldenring let me know if it still looks warped for you? I changed the sizing to see if that would help

**Comment by kate-goldenring** [comment]
> > nit: can we keep the diagram name `opcua-demo-diagram`? Also the updated diagram seems malformed on the `SomeServer0` and `1`. may just be my viewer, though
> 
> @kate-goldenring let me know if it still looks warped for you? I changed the sizing to see if that would help

@yujinkim-msft this still looks warped to me. Does it look fine for you? https://github.com/yujinkim-msft/akri-docs/blob/updated-opcua-plc-demo/docs/demos/opc-thermometer-demo.md

**Comment by yujinkim-msft** [comment]
> > > nit: can we keep the diagram name `opcua-demo-diagram`? Also the updated diagram seems malformed on the `SomeServer0` and `1`. may just be my viewer, though
> > 
> > 
> > @kate-goldenring let me know if it still looks warped for you? I changed the sizing to see if that would help
> 
> @yujinkim-msft this still looks warped to me. Does it look fine for you? https://github.com/yujinkim-msft/akri-docs/blob/updated-opcua-plc-demo/docs/demos/opc-thermometer-demo.md

It looks okay to me.... According to @adithyaj it looks fine for him too.... Would it be better if I uploaded a PNG file instead of SVG? Maybe it is scaling strangely the way I edited it

**Review by kate-goldenring — APPROVED** [review]

**Pull request merged**
