### PR TITLE
Added missing dependency and updated cargo version

### PR DESCRIPTION
**Pull request by bindsi**
- updated cargo version in the toolchain install instruction to version 1.70 as it is required by cargo-generate which is used to create a discovery-handler project from a template
- added "html" package import to the Go module for the http server because it is required as dependency in the build step (docker build)

### CODE REVIEW

**Review by diconico07 — APPROVED** [review]

**Comment by Bindsi** [comment]
@diconico07 who is gonna merge this?

**Comment by diconico07** [comment]
@Bindsi , I will in a few days, or some other maintainers if they take a look before that. We tend to let a bit of time for other reviewers to have another look before merging after an approval.

**Review by johnsonshih — APPROVED** [review]

**Review by johnsonshih — COMMENTED** [review]
the akri repo setup.sh still use 1.68.1, do we need to update rust version in code repo, too?

**Comment by Bindsi** [comment]
> the akri repo setup.sh still use 1.68.1, do we need to update rust version in code repo, too?

@johnsonshih: yeah, you are right...but I see that it is not compiling with 1.70 because dependencies require 1.68.1 and are tightly coupled to that version by the cargo.lock checked in in codebase...mmh, wondering if I should create an issue for that and trying to resolve it...wdyt?

**Comment by johnsonshih** [comment]
> > the akri repo setup.sh still use 1.68.1, do we need to update rust version in code repo, too?
> 
> @johnsonshih: yeah, you are right...but I see that it is not compiling with 1.70 because dependencies require 1.68.1 and are tightly coupled to that version by the cargo.lock checked in in codebase...mmh, wondering if I should create an issue for that and trying to resolve it...wdyt?

please create an issue to keep track of the problem, thanks!

**Comment by kate-goldenring** [comment]
created a pr to bump to latest rust version for Akri: https://github.com/project-akri/akri/pull/679

**Review by kate-goldenring — APPROVED** [review]

**Pull request merged**
